[package]
name = "yew-preview"
version = "0.3.1"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr", "ssr"] }
paste = "1.0"
web-sys = { version = "0.3", features = ["HtmlInputElement"] }

[dev-dependencies]
tokio = { version = "1.0", features = ["macros"] }
