[package]
name = "yew-preview"
version = "0.3.0"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr", "ssr"] }
paste = "1.0"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros"] }
