name: GitHub Pages Deployment

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build_and_deploy:
    name: Build and Deploy to GitHub Pages
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Cache Cargo Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - name: Build with Trunk
        run: trunk build --release --dist ./dist --public-url /yew-preview/
        env:
          RUST_LOG: trunk=info

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          keep_files: true
          force_orphan: true

      - name: Run code formatter
        run: cargo fmt --all -- --check

      - name: Run linter
        run: cargo clippy -- -D warnings
